#!/bin/bash -l
#SBATCH -p debug
#SBATCH -N 20
#SBATCH -t 00:10:00
#SBATCH -J my_job
#SBATCH -o slurm.o%j
#SBATCH -L SCRATCH

#Edison has 24 cores per compute node
srun -n 240 ./AmrDeriveIsoSec_withgrad3d.Linux.Intel.Intel.MPI.DODECANE_LU.ex  inputs infile = /scratch1/scratchdirs/dalakoti/_coarse/plt_hwk_03520







